### ISSUE TITLE
Reduce amount of requests sent to display experiment status

### ISSUE THREAD

**Issue by relet** [MONROE-PROJECT/UserAccess#3]
The API request for experiments should contain status codes for all scheduling entries, so that it is not/no longer necessary to send one request per scheduling entry.

**Comment by relet** [comment]
To explain - on my not-so-glorious Internet connection, to display a recurring experiment (#955, with ~1300 tasks)
- 3.6 MB and 25s to display the experiment list
- 1.1 MB and 140s to display the status, once you click on the experiment.

**Comment by mikepeon** [comment]
Considering that asking for the experiments of a user retrieves ALL the experiments + ALL the schedules, wouldn't it be better not to send the scheduling info with the experiments, so that this is transferred only on demand?
For user 124, getting the list of experiments takes about 10s in the server side (!!) and transfers almost 6 MB.

**Comment by relet** [comment]
Yes, I guess we need pagination for both cases.
Can you suggest what you need and what the requests should look like? The schedules request accepts a start and stop time, but I guess a count and offset might be more useful.

**Comment by mikepeon** [comment]
I think that pagination is maybe not ideal because we would be transferring a lot of info as well, when the user will mostly click only on one or two experiments.
Maybe experiments can send only the list of their scheduleIDs, and then I can ask for them, or a new method to ask for the schedules of an experimentID.
However, we would need to get the "completed" flag for the experiments, as currently I iterate thru the list of schedules of each experiment to calculate it...

**Comment by relet** [comment]
Ok, then I suggest that we revert to sending only the scheduling IDs, and a status summary for the experiment in the form
{"defined":"50", "started":1, "failed":0, "finished":12} - from that you can create either a yes/no flag, a percentage or another detail.

**Comment by mikepeon** [comment]
That would be fine. The request should look like this:
https://scheduler.monroe-system.eu/v1/users/124/experiments
[
    {
        "id": 310,
        "name": "HTTP",
        "options": {
            "shared": 0,
            "storage": 104857600,
            "traffic": 1048576
        },
        "ownerid": 124,
        "schedules": [5975, 5976, 5977],
        "defined": 2,
        "started": 1,
        "finished": 0
    },
]
THEN, when the user clicks on an experiment, I'll use the existing query to get its schedules:
https://scheduler.monroe-system.eu/v1/experiments/955

**Comment by relet** [comment]
I would just suggest to nest it: 

```
...
"schedules": [5975, 5976, 5977],
"summary":{
    "defined": 2,
    "started": 1,
    "finished": 0
},
...
```

Ok?

**Comment by mikepeon** [comment]
Sure. Just tell me when it's implemented to try it and adapt the code.

**Comment by relet** [comment]
Please check 
https://scheduler.monroe-system.eu:4443/v1/experiments/54 
https://scheduler.monroe-system.eu:4443/v1/users/19/experiments
and 
https://scheduler.monroe-system.eu:4443/v1/experiments/54/schedule/98dev

**Comment by mikepeon** [comment]
With the agred modifications, now the experiment list contains only a listing of the schedules of an experiment and the summary of execution states (how many finished, etc). When the user clicks, a single query is executed to retrieve all the information for that experiment.
For user 124, the listing now transfers 787KB and clicking on experiment 955 produces one single query of  162 KB.

**Comment by mikepeon** [comment]
Modification is finished. Needs further testing.
